version: "3"

services:
  api:
    image: torchserve:test
    stdin_open: true # docker run -i
    tty: true # docker run -t
    volumes:
      - /home/tintr/Documents/personal/torch-serve/:/home/torch-serve
    ports:
      - 8001:8001
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["0"]
              capabilities: [gpu]
    # command: sh -c "torchserve --start --ncs --model-store model-store --models face-car-plate-window.mar"
    # command: sh -c "ls"

    